### ISSUE TITLE
Unable to compile with GCC_ARM: rt_TypeDef.h: No such file or directory

### ISSUE THREAD

**Issue by sergiuszm** [nuket/mbed-memory-status#6]
Hello,

I am trying to compile my code with your library, but I don't have **rt_TypeDef.h** file. Is your library working only with KEIL compiler?

Thanks for help.

--
EDIT

I am using mbed-os 5.5. It looks like the issue is not related to KEIL compiler but to structure change of RTOS in mbed-os 5.5. This file doesn't exist anymore in that version of mbed-os.

**Comment by nuket** [comment]
Actually, I only have used it with GCC. But if that is an RTX header, it 
should be part of the mbed OS checkout already. Sounds like a dependency 
issue in the target port of your board, the mbed-memory-staus source code 
doesn't directly include that file.

**Comment by sergiuszm** [comment]
@nuket the mbed-memory-status source code does directly include that file:
line 192-197
```
#if (defined (MBED_CONF_RTOS_PRESENT) && (MBED_CONF_RTOS_PRESENT != 0))
#include "cmsis_os.h"

// Temporarily #undef NULL or the compiler complains about previous def.
#undef NULL
#include "rt_TypeDef.h"
```

Unfortunately, this file no longer exists in mbed-os 5.5.

**Comment by nuket** [comment]
Looks like you're out of luck on this one. Even removing that `#include` statement to see what happens, the required structures and functions have been removed:

```
Compile [  4.2%]: mbed_memory_status.c
[Error] mbed_memory_status.c@200,8: unknown type name 'P_TCB'
[Error] mbed_memory_status.c@208,5: unknown type name 'P_TCB'
[Error] mbed_memory_status.c@211,28: invalid type argument of '->' (have 'int')
[Warning] mbed_memory_status.c@213,13: implicit declaration of function '_osThreadGetInfo' [-Wimplicit-function-declaration]
[Error] mbed_memory_status.c@213,40: 'osThreadInfoStackSize' undeclared (first use in this function)
[Error] mbed_memory_status.c@216,41: invalid type argument of '->' (have 'int')
[Error] mbed_memory_status.c@221,40: 'osThreadInfoStackMax' undeclared (first use in this function)
[Error] mbed_memory_status.c@231,40: 'osThreadInfoEntry' undeclared (first use in this function)
[Error] mbed_memory_status.c@240,5: unknown type name 'osThreadEnumId'
[Warning] mbed_memory_status.c@240,31: implicit declaration of function '_osThreadsEnumStart' [-Wimplicit-function-declaration]
[Warning] mbed_memory_status.c@243,24: implicit declaration of function '_osThreadEnumNext' [-Wimplicit-function-declaration]
[Warning] mbed_memory_status.c@243,22: assignment makes pointer from integer without a cast [-Wint-conversion]
[Warning] mbed_memory_status.c@248,5: implicit declaration of function '_osThreadEnumFree' [-Wimplicit-function-declaration]
[ERROR] .\mbed-memory-status\mbed_memory_status.c:200:8: error: unknown type name 'P_TCB'
 extern P_TCB rt_tid2ptcb (osThreadId thread_id);
        ^~~~~
.\mbed-memory-status\mbed_memory_status.c: In function 'print_thread_info':
.\mbed-memory-status\mbed_memory_status.c:208:5: error: unknown type name 'P_TCB'
     P_TCB tcb = rt_tid2ptcb(threadId);
     ^~~~~
.\mbed-memory-status\mbed_memory_status.c:211:28: error: invalid type argument of '->' (have 'int')
     debug_print_pointer(tcb->stack);
                            ^~
.\mbed-memory-status\mbed_memory_status.c:213:13: warning: implicit declaration of function '_osThreadGetInfo' [-Wimplicit-function-declaration]
     event = _osThreadGetInfo(threadId, osThreadInfoStackSize);
             ^~~~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c:213:40: error: 'osThreadInfoStackSize' undeclared (first use in this function)
     event = _osThreadGetInfo(threadId, osThreadInfoStackSize);
                                        ^~~~~~~~~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c:213:40: note: each undeclared identifier is reported only once for each function it appears in
.\mbed-memory-status\mbed_memory_status.c:216:41: error: invalid type argument of '->' (have 'int')
     debug_print_pointer(((uint8_t *) tcb->stack + event.value.v)); // (tcb->priv_stack)));
                                         ^~
.\mbed-memory-status\mbed_memory_status.c:221:40: error: 'osThreadInfoStackMax' undeclared (first use in this function)
     event = _osThreadGetInfo(threadId, osThreadInfoStackMax);
                                        ^~~~~~~~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c:231:40: error: 'osThreadInfoEntry' undeclared (first use in this function)
     event = _osThreadGetInfo(threadId, osThreadInfoEntry);
                                        ^~~~~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c: In function 'print_all_thread_info':
.\mbed-memory-status\mbed_memory_status.c:240:5: error: unknown type name 'osThreadEnumId'
     osThreadEnumId enumId   = _osThreadsEnumStart();
     ^~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c:240:31: warning: implicit declaration of function '_osThreadsEnumStart' [-Wimplicit-function-declaration]
     osThreadEnumId enumId   = _osThreadsEnumStart();
                               ^~~~~~~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c:243:24: warning: implicit declaration of function '_osThreadEnumNext' [-Wimplicit-function-declaration]
     while ((threadId = _osThreadEnumNext(enumId)))
                        ^~~~~~~~~~~~~~~~~
.\mbed-memory-status\mbed_memory_status.c:243:22: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     while ((threadId = _osThreadEnumNext(enumId)))
                      ^
.\mbed-memory-status\mbed_memory_status.c:248:5: warning: implicit declaration of function '_osThreadEnumFree' [-Wimplicit-function-declaration]
     _osThreadEnumFree(enumId);
     ^~~~~~~~~~~~~~~~~
```

Grepping for the structures and functions in the mbed OS source, reveals that they are gone. 

So the last version you can use this code with directly is `mbed-os-5.4.7`. I'm not sure what the deprecation policy of mbed is, but I'm guessing low-level APIs aren't covered by any guarantee.

There are probably similar data structures in CMSIS-RTOS2, but this will take some effort to port in. 

Also not helpful, there are no semantic versioning `#define`s when `mbed compile` is executed, which would make writing conditionally compiled code slightly more difficult.

**Comment by sergiuszm** [comment]
Thanks @nuket. I tried to find corresponding methods in mbed-os-5.5 but the low-level API was removed.

Maybe I will have some spare time in the future to rewrite your code to get it working with mbed-os-5.5 but I can not promise anything right now.
